@extends('layouts.master')

@section('title', 'Bill Sheet Details')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow-sm">
                <div class="card-header bg-white d-flex justify-content-between align-items-center flex-wrap gap-2">
                    <h5 class="mb-0 fw-bold text-dark">
                        <i class="fas fa-file-invoice text-primary me-1"></i> Bill Sheet Details
                    </h5>
                    <div>
                        <a href="{{ route('bill-sheets.pdf', $billSheet->id) }}" class="btn btn-danger btn-sm">
                            <i class="fas fa-file-pdf me-1"></i> PDF
                        </a>
                        <a href="{{ route('bill-sheets.edit', $billSheet->id) }}" class="btn btn-warning btn-sm">
                            <i class="fas fa-edit me-1"></i> Edit
                        </a>
                        <a href="{{ route('bill-sheets.index') }}" class="btn btn-secondary btn-sm">
                            <i class="fas fa-arrow-left me-1"></i> Back
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <table class="table table-bordered">
                                <tr>
                                    <th width="30%">Name</th>
                                    <td>{{ $billSheet->name }}</td>
                                </tr>
                                <tr>
                                    <th>Class</th>
                                    <td>{{ $billSheet->studentClass->name ?? 'N/A' }}</td>
                                </tr>
                                <tr>
                                    <th>Academic Year</th>
                                    <td>{{ $billSheet->academicYear->name ?? 'N/A' }}</td>
                                </tr>
                                <tr>
                                    <th>Term</th>
                                    <td>{{ $billSheet->term->name ?? 'N/A' }}</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-bordered">
                                <tr>
                                    <th width="30%">Generated Date</th>
                                    <td>{{ $billSheet->generated_date->format('d-m-Y') }}</td>
                                </tr>
                                <tr>
                                    <th>Due Date</th>
                                    <td>{{ $billSheet->due_date ? $billSheet->due_date->format('d-m-Y') : 'N/A' }}</td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>
                                        <span class="badge bg-{{ $billSheet->status == 'draft' ? 'secondary' : 
                                            ($billSheet->status == 'pending' ? 'warning' : 
                                            ($billSheet->status == 'approved' ? 'success' : 
                                            ($billSheet->status == 'rejected' ? 'danger' : 'info'))) }}">
                                            {{ ucfirst($billSheet->status) }}
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Generated By</th>
                                    <td>{{ $billSheet->generatedBy->name ?? 'N/A' }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="table-light">
                                <tr>
                                    <th>#</th>
                                    <th>Item Name</th>
                                    <th>Fee Category</th>
                                    <th class="text-end">Amount</th>
                                    <th class="text-center">Qty</th>
                                    <th class="text-end">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($billSheet->items as $index => $item)
                                    <tr>
                                        <td>{{ $index + 1 }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->feeCategory->name ?? 'N/A' }}</td>
                                        <td class="text-end">GHS {{ number_format($item->amount, 2) }}</td>
                                        <td class="text-center">{{ $item->quantity }}</td>
                                        <td class="text-end">GHS {{ number_format($item->total_amount, 2) }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr class="table-light">
                                    <td colspan="5" class="text-end fw-bold">Sub Total:</td>
                                    <td class="text-end fw-bold">GHS {{ number_format($billSheet->total_amount, 2) }}</td>
                                </tr>
                                <tr class="table-light">
                                    <td colspan="5" class="text-end fw-bold">Discount:</td>
                                    <td class="text-end text-danger fw-bold">- GHS {{ number_format($billSheet->discount_amount, 2) }}</td>
                                </tr>
                                <tr class="table-light">
                                    <td colspan="5" class="text-end fw-bold">Tax:</td>
                                    <td class="text-end text-warning fw-bold">+ GHS {{ number_format($billSheet->tax_amount, 2) }}</td>
                                </tr>
                                <tr class="table-success">
                                    <td colspan="5" class="text-end fw-bold fs-5">Grand Total:</td>
                                    <td class="text-end fw-bold fs-5">GHS {{ number_format($billSheet->net_amount, 2) }}</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                    @if($billSheet->description)
                        <div class="mt-3">
                            <strong>Description:</strong>
                            <p>{{ $billSheet->description }}</p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection